#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace SquirreltemGameplayTags
{
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemGrade_Common);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemGrade_Uncommon);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemGrade_Rare);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemGrade_Unique);

	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MetaData_Durability);

	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstData_MaxDurability);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstData_ItemUseType);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstData_SocketName);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstData_GeneratedItemId);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstData_ChanceBasedSpawnItemId);
	SQUIRRELTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstData_ItemGrade);
}
